
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    env_file:
      - .prod.env  # Load environment variables from .prod.env file
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'  # Use environment variable
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'  # Use environment variable
      - 'POSTGRES_USER=${POSTGRES_USER}'  # Use environment variable
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data  # Persist data in a Docker volume

  spring-blog-app:
    build: .  # Builds from Dockerfile in current directory
    depends_on:
      - 'postgres'
    container_name: spring-blog-app
    env_file:
      - '.prod.env'  # Load environment variables from .prod.env file
    environment:
      # Spring Mail Configuration (Google SMTP)
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${SMTP_USER}  # Use environment variable
      SPRING_MAIL_PASSWORD: ${SMTP_PASSWORD}  # Use app password!

      # SMTP Properties
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

      # cors config
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/BlogAPI
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_MVC_CORS_ALLOWED-ORIGINS: '*'
      SPRING_MVC_CORS_ALLOWED-METHODS: GET,POST,PUT,DELETE,OPTIONS
      SPRING_MVC_CORS_ALLOWED-HEADERS: '*'
      SERVER_ERROR_INCLUDE-MESSAGE: always
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG

      # Other Spring properties (optional)
      SERVER_PORT: 8080
    ports:
      - "8080:8080"  # Host:Container port mapping

volumes:
  db-data:
