
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    env_file:
      - .prod.env  
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - '5432:5432'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/

  spring-blog-app:
    build: . 
    depends_on:
      - 'postgres'
    container_name: spring-blog-app
    env_file:
      - '.prod.env'  
    environment:
      
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${SMTP_USER}
      SPRING_MAIL_PASSWORD: ${SMTP_PASSWORD}
      SPRING_MAIL_PROTOCOL: smtp
      SPRING_MAIL_TEST_CONNECTION: "false"
      SPRING_MAIL_DEFAULT_ENCODING: UTF-8


      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT: 5000
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT: 3000
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT: 5000
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: smtp.gmail.com

      # cors config
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_MVC_CORS_ALLOWED_ORIGINS: '*'
      SPRING_MVC_CORS_ALLOWED_METHODS: GET,POST,PUT,DELETE,OPTIONS
      SPRING_MVC_CORS_ALLOWED_HEADERS: '*'
      SERVER_ERROR_INCLUDE_MESSAGE: always
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG

      UPLOAD_DIRECTORY: /app/uploads/images
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 5MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB
      SERVER_PORT: 8080
    ports:
      - "8080:8080"  # Host:Container port mapping
    volumes:
      - upload-data:/app/uploads

volumes:
  upload-data: 
